### ISSUE TITLE
Missing UI Elements in titlebar/tabbar on macOS in 2020.01

### ISSUE THREAD

**Issue by jrappen** [MrAlex94/Waterfox#1357]
### Description

Waterfox 2020.01 on macOS is missing UI Elements in the titlebar / tabbar.

### Screenshots

<img width="842" alt="image" src="https://user-images.githubusercontent.com/8577450/72254519-91140980-3604-11ea-9c56-26912f39f7c3.png">

### Configuration

```yaml
Waterfox:
  build: 2020.01
  channel: current
    portable: false
  platform: osx x64
    version: macOS Catalina 10.15.2 (19C57)
  hardware: MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
```
