### ISSUE TITLE
Opacity not working

### ISSUE THREAD

**Issue by edazpotato** [MrAlex94/Waterfox#1734]
**Describe the bug**
The css `opacity` property does not work properly when animated. 

E.g.
```css
.class {
    opacity: 0%;
    transition-duration: 1s;
}
.class:hover {
    opacity: 100%;
}
```

**To Reproduce**
1. Go to a website that uses animated opacity somewhere 
2. Note that it just displays at full opacity

**Expected behavior**
The opacity of the text or elements should change

**Screenshots**

**My configuration** 
 - Device: PC
 - OS: Windows 10
 - Version: 2020.08.1

**Additional context**
