### ISSUE TITLE
I recommend updating the Lepton code.

### ISSUE THREAD

**Issue by black7375** [MrAlex94/Waterfox#2584]
### What happened?

I found the next commit while looking at the repository.  https://github.com/WaterfoxCo/Waterfox/commit/f92e95c09ecd98f987bf54e1e6a1cf969b683277

While working on [Firefox `v96` compatibility](https://github.com/black7375/Firefox-UI-Fix/issues/318), I had a reimplementation on the tab height.
But there were several critical bugs. (Lepton `v4.5.8`)

- Pinned Tab - Vertical align https://github.com/black7375/Firefox-UI-Fix/issues/330
- Tab - toolbar top line at compact https://github.com/black7375/Firefox-UI-Fix/issues/333
- Tab - toolbar top line at linux https://github.com/black7375/Firefox-UI-Fix/issues/334

I released `v4.5.9` to resolve the above problems and recommends updates.

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

G4.𝑋 (Future)

### What platform are you seeing the problem on?

Linux

**Comment by MrAlex94** [comment]
Thanks, appreciate you filing an issue for this! I typically update Lepton before next update, and have done so with this commit: https://github.com/WaterfoxCo/Waterfox/commit/a4251ef0a08f313f18f22904e814aa71cb8f4fb6

Thanks once again :-)

**Comment by black7375** [comment]
I have a plan to enhance support for Waterfox.
There seem to be two changes except for changing the icon path.

https://github.com/WaterfoxCo/Waterfox/blob/a4251ef0a08f313f18f22904e814aa71cb8f4fb6/browser/themes/addons/lepton/userChrome.css#L1190-L1196

https://github.com/WaterfoxCo/Waterfox/blob/a4251ef0a08f313f18f22904e814aa71cb8f4fb6/browser/themes/addons/lepton/userChrome.css#L2616-L2623

It seems to be a compatibility issue, is there any related issue?
If it is the same code base, it will be easy to update because we only need to write icon-specific path scripts.

**Comment by MrAlex94** [comment]
@black7375, thanks! I was going to submit issues in the repo regarding them.

```CSS
 /* Waterfox */ 
 .autocomplete-richlistitem:hover { 
   background-color: var(--arrowpanel-dimmed) !important; 
 } 
 ```
The above is so that when hovering over a search selection, it highlights the item. Sadly doesn't work when navigating with keyboard arrows.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/4728920/155568171-a35011bd-da0b-4523-8ff1-3ed2a3a5bec9.png">

```CSS
 #tabbrowser-tabs:not([movingtab]) .tabbrowser-tab:not([collapsed]) { 
   /* -moz-box-flex may be caused #tabbrowser-tabs[closebuttons] */ 
   transition: -moz-box-flex 0.2s var(--animation-easing-function), 
     margin-inline-start 0.2s var(--animation-easing-function), min-width 0.1s ease-out, max-width 0.1s ease-out !important; 
   /* Waterfox */ 
   /* max-width: var(--tab-max-width, 240px); */ 
 } 
 ```

I commented out max-width, because for some reason it won't move the tabs together when one is closed otherwise:
![image](https://user-images.githubusercontent.com/4728920/155569135-1c089e78-df39-4e28-afed-5161e3337fbc.png)
