### ISSUE TITLE
sidebar not resizable when put on the right

### ISSUE THREAD

**Issue by ghost** [MrAlex94/Waterfox#2825]
### What happened?

when I put the sidebar on the right part of the window it is not resizable anymore.
when I put it again on the left then it is resizable as usual.

on firefox 105 it works correctly (ie sidebar is resizable when on the left).

tested on waterfox 5.01 on windows 10

### Reproducible?

- [ ] I have tested this on Firefox.

### Version

Other

### What platform are you seeing the problem on?

Windows

**Comment by lazymonkey2** [comment]
can confirm this issue when using your default theme.
if I change the theme then I can resize even when sidebar is on right side.
I'm currently using this theme:
https://addons.mozilla.org/en-US/firefox/addon/activist-balanced/

**Comment by rubaboo** [comment]
The bug is still there in the latest. Using a different non-default theme, still can't resize when on the right.

Also can't resize when the Tabs Sidebar is closed... Speaking of which, Tabs Sidebar needs to stay on the outside of the default  sidebar. Otherwise it ends up in between the sidebar and content page, which is especially undesirable when using Side View extension.

**Comment by rubaboo** [comment]
As mentioned earlier, IMO Tabs sidebar has to stay at the outer edge, on whichever side. This userChrome style seems to do the trick:
```css

:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) ~ #tabs-sidebar-box {
  order: 1 !important;
}
:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) ~ #tabs-sidebar-splitter {
  order: 2 !important;
}
:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) {
  order: 3 !important;
}:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) ~ #sidebar-splitter {
  order: 4 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] ~ #sidebar-splitter {
  order: 2 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] {
  order: 3 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] ~ #tabs-sidebar-splitter {
  order: 4 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] ~ #tabs-sidebar-box {
  order: 5 !important;
}
```
