### ISSUE TITLE
Tabs Sidebar needs to remain on the outer edge of the window

### ISSUE THREAD

**Issue by rubaboo** [MrAlex94/Waterfox#3650]
**Is your feature request related to a problem? Please describe.**
When Bookmarks or any other sidebar is open, Tabs Sidebar is positioned between that and the content frame. It doesn't look good, especially if the other sidebar is used for Side View.

**Describe the solution you'd like**
Tabs Sidebar needs to remain on the outer edge of the window (left or right, whichever is chosen).

**Describe alternatives you've considered**
Currently using this in my `userChrome.css` and it seems to do the trick:
```css
:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) ~ #tabs-sidebar-box {
  order: 1 !important;
}
:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) ~ #tabs-sidebar-splitter {
  order: 2 !important;
}
:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) {
  order: 3 !important;
}:root:not(.tabs-sidebar-right) #sidebar-box:not([positionend="true"]) ~ #sidebar-splitter {
  order: 4 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] ~ #sidebar-splitter {
  order: 2 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] {
  order: 3 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] ~ #tabs-sidebar-splitter {
  order: 4 !important;
}
:root.tabs-sidebar-right #sidebar-box[positionend="true"] ~ #tabs-sidebar-box {
  order: 5 !important;
}
```
