### ISSUE TITLE
Custom set colors through userChrome.css ignored/broken since 6.5.5

### ISSUE THREAD

**Issue by linkoviccsumoszky** [MrAlex94/Waterfox#3725]
### What happened?

Since version 6.5.5, when the _system theme_ is the active skin, userChrome.css customizations (regarding the bg-colors of the tab bar and menu bar) are not applied as expected. It seems to only affect bright mode when the browser window is in focus **and** the title bar is hidden.

Expected looks (userChrome.css overwrites system-accent colors as it should):
![Image](https://github.com/user-attachments/assets/77b5194a-15a1-415e-b470-f3e1fa966f5a)

Looks like this since 6.5.5 (system-accent color is used as bg to tab-bar and menu-bar instead of user preference):
![Image](https://github.com/user-attachments/assets/711f1934-0ebd-45b1-8e3a-d6518f6872e4)

### Reproducible?

- [x] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell

```

**Comment by linkoviccsumoszky** [comment]
Upon further investigation, I realized this is a recurring problem: _https://github.com/BrowserWorks/Waterfox/issues/2369_
But as expected, nothing has changed since I reported it. I even doubt anyone from the devs side reads these bug reports anymore.

**Comment by Kol9yN** [comment]
Can confirm, i added this in userChrome.css, i trying to change context line color, but it doesn't works
```css
.tab-text.tab-label {
	font-size:12px;
}

/* adds the little colored strip on top of the selected tab */
.tab-background:is([selected], [multiselected]) {
  box-shadow: inset 0 2px var(--selected-tab-strip, --custom-accent-color, #FF8000) !important;
  border: 0 !important;
  outline: none !important;
  background-repeat: no-repeat !important;
}

```
Any ideas?
